# Generated by Django 4.2.9 on 2024-01-09 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('location', django_jsonform.models.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('delivery_time_window', django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', django_jsonform.models.fields.ArrayField(base_field=models.FloatField(), size=2)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='items',
            field=models.ManyToManyField(through='v1.WarehouseItem', to='v1.item'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('end', django_jsonform.models.fields.ArrayField(base_field=models.FloatField(), default=list, size=2)),
                ('start', django_jsonform.models.fields.ArrayField(base_field=models.FloatField(), default=list, size=2)),
                ('time_window', django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2)),
                ('skills', models.ManyToManyField(to='v1.skill')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='v1.OrderItem', to='v1.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='required_skills',
            field=models.ManyToManyField(to='v1.skill'),
        ),
    ]
