# Generated by Django 4.2.9 on 2024-01-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='required_skills',
            field=models.ManyToManyField(to='v1.skill'),
        ),
    ]
