# Generated by Django 4.2.9 on 2024-01-06 17:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_skill_vehicle_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('delivery_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='v1.OrderItem', to='v1.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='required_skills',
            field=models.ManyToManyField(to='v1.skill'),
        ),
    ]
