# Generated by Django 4.2.9 on 2024-01-06 20:29

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_item_order_orderitem_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=django_jsonform.models.fields.ArrayField(base_field=models.FloatField(), size=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
